global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    prometheus_replica: replica-2

scrape_configs:
  - job_name: "prometheus-1"
    static_configs:
      - targets: ["host.docker.internal:9091"]
  - job_name: "prometheus-2"
    static_configs:
      - targets: ["host.docker.internal:9092"]

remote_write:
  - url: http://host.docker.internal:8080/write
    # headers:
    #   X-Ridley-Replica: replica-2