services:
  prometheus1:
    image: prom/prometheus:v3.5.0
    container_name: prometheus1
    volumes:
      - ./prom1:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.listen-address=0.0.0.0:9091'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9091:9091
    depends_on:
      - prometheus-central
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prometheus2:
    image: prom/prometheus:v3.5.0
    container_name: prometheus2
    volumes:
      - ./prom2:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.listen-address=0.0.0.0:9092'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9092:9092
    depends_on:
      - prometheus-central
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prometheus-central:
    image: prom/prometheus:v3.5.0
    container_name: prometheus-central
    volumes:
      - ./prom-recv:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.listen-address=0.0.0.0:9090'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"