global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    prometheus_replica: replica-1

scrape_configs:
  - job_name: "prometheus-1"
    static_configs:
      - targets: ["localhost:9091"]
  - job_name: "prometheus-2"
    static_configs:
      - targets: ["localhost:9092"]

remote_write:
  # write to Ridley
  - url: http://host.docker.internal:8080/write
    headers:
      X-Ridley-Replica: replica-1
  # - url: http://prometheus-central:9090/api/v1/write
#    protobuf_message: io.prometheus.write.v2.Request
